before_install:
- openssl aes-256-cbc -K $encrypted_a12191e97ed0_key -iv $encrypted_a12191e97ed0_iv
  -in .chef/jonathanmorley.pem.enc -out .chef/jonathanmorley.pem -d
language: ruby
sudo: false
rvm: 2.2.2
